### ISSUE TITLE
Is it possible to adjust speaking rate and pitch?

### ISSUE THREAD

**Issue by craigrenn** [takoz53/TwitchTTS#11]
AudioConfig within google.cloud.texttospeech.v1 has a couple of options for "speaking_rate" and "pitch".
https://cloud.google.com/text-to-speech/docs/reference/rpc/google.cloud.texttospeech.v1

Could these be added as options in the options.txt and/or assigned to individuals in the usernames.json?

**Comment by takoz53** [comment]
I'll be looking into it!

**Comment by takoz53** [comment]
@craigrenn are u able to compile the newest piece of code and test it perhaps? I don't have a google cloud account to do so. If not, It might take a bit more to push the newest update.

**Comment by craigrenn** [comment]
I'm not really familiar with compiling, but I gave it shot. I ran into an error. Let me know if you need a bit more info. I opened the TextToSpeechTTV.csproj in visualstudio 2019 and started in debug. I filled out the options and authorizations in the command prompt. Then I got an error in line 279 of TestToSpeechTTV.Config :
string gcp = optionsList[11].ToLower();

System.NullReferenceException: 'Object reference not set to an instance of an object.'
optionsList was null.

![Error Message](https://user-images.githubusercontent.com/91448875/135737576-fb4ef080-3f35-4e82-827f-a18a2dfcd812.PNG)

**Comment by takoz53** [comment]
Thank you, useful information. I'll give it a look!
