### ISSUE TITLE
TTS doesnt works

### ISSUE THREAD

**Issue by connager** [takoz53/TwitchTTS#13]
Hi! Program says that "TTS Name does not exist. TTS will NOT work.". I dont know what can be wrong.
![image](https://user-images.githubusercontent.com/94758210/142736547-c14c1c04-3bc3-418a-a0ba-632e6b41a151.png)
![image](https://user-images.githubusercontent.com/94758210/142736550-37f99dfb-93f8-4c59-8ff8-7d2d908b5272.png)

**Comment by takoz53** [comment]
Your TTS Voice is set to "Microsoft David Desktop". You only have "Microsoft Irina Desktop" and "Microsoft Zira Desktop".

**Comment by connager** [comment]
Hi again. Theres no issues with tts name anymore, but i have another. I set all parameters but it just wont work
![image](https://user-images.githubusercontent.com/94758210/142755605-f95f1bfc-c9c0-427c-8f32-0ac2e932923d.png)
![image](https://user-images.githubusercontent.com/94758210/142755606-19b58007-7fd0-4193-8f6e-a42569cbcf1b.png)
![image](https://user-images.githubusercontent.com/94758210/142755655-757a0618-da49-4ebb-a249-ce575c28b4e5.png)
