### ISSUE TITLE
It just wont wok

### ISSUE THREAD

**Issue by connager** [takoz53/TwitchTTS#14]
Hi again. Theres no issues with tts name anymore, but i have another. I set all parameters but it just wont work
![image](https://user-images.githubusercontent.com/94758210/142908523-723a76b2-49b2-4bfd-ac84-068dfe3da98f.png)
![image](https://user-images.githubusercontent.com/94758210/142908528-98641b8c-d36a-4677-bd49-54adc6191a66.png)
![image](https://user-images.githubusercontent.com/94758210/142908534-baf4c0cf-30e6-4814-bf5d-598c6abc4472.png)

**Comment by takoz53** [comment]
Hello,

there is 2 config files. You only set the authentification.

There is another file with various setting. If you want TTS to be enabled with channel points, change Bound Channel Name to "TTS" (or however your reward is named. I see it is TTS so I said TTS).
![sublime_text_8gxYMl1qZi](https://user-images.githubusercontent.com/16865864/143076773-d093dc6d-899f-4b57-b838-4b9bee2654c3.png)
s
