### ISSUE TITLE
Everything is setted but it still dont work.

### ISSUE THREAD

**Issue by connager** [takoz53/TwitchTTS#15]
![image](https://user-images.githubusercontent.com/94758210/143083085-197a9cae-7b05-4b91-a65e-3b29bc590595.png)
![image](https://user-images.githubusercontent.com/94758210/143083113-1ecfda3a-f495-4131-a2ce-ef48fd5a4255.png)
![image](https://user-images.githubusercontent.com/94758210/143083157-a00d6d1b-512d-4e04-9f58-802506ea4558.png)
![image](https://user-images.githubusercontent.com/94758210/143083185-00981d16-a4d0-491b-ba07-e8955726d4f0.png)
Can u leave your mail or somethink that i can write you if something not working without opening new issue? :)

**Comment by takoz53** [comment]
Discord たここ#8182 I'll check

**Comment by takoz53** [comment]
ChannelID should be numbers only. Fixed by fixing userinput.
