### ISSUE TITLE
could you make Google cloud TTS integrate with this

### ISSUE THREAD

**Issue by Defalt624** [takoz53/TwitchTTS#4]
as title. Thx.

**Comment by takoz53** [comment]
I do not understand your question, sorry?

**Comment by Defalt624** [comment]
Yeah im not a coder so i don't know how to put this.
Currently this TTS you wrote only uses microsoft voices.
And I don't want to use IVANA voices because it only supports English.
I'm asking if you could make Google cloud TTS as option.

**Comment by takoz53** [comment]
Ah, I understand. It doesn't only use microsoft voices, it uses the voices you have installed on your computer. The problem with google services is, they cost money always. You have to get its voice somehow installed on your computer. I don't think I can resolve this issue! Sorry!

**Comment by Defalt624** [comment]
Do you recommend any voices beside Microsoft and IVANA then?

**Comment by takoz53** [comment]
I am unsure about any other voices, I'm sorry about that ;_; Feel free to let me know if u have other issues.
