### ISSUE TITLE
The ability to only read a specific channel points when redeemed, so like tts points

### ISSUE THREAD

**Issue by ftk789** [takoz53/TwitchTTS#7]
The ability to only read a specific channel points when redeemed, so like tts points

**Comment by takoz53** [comment]
If I understand correctly, you want to bind TTS to channel points, correct? e.g. 1000 Points option redeems TTS, is that correct? I'll check into it.

**Comment by ftk789** [comment]
Yea so like someone redeems a 10K channel point followed with a text, then a tts plays the tts, im still waiting for the windows release so i see how it works, but yea if there is a "play tts only with channel points redeemed" would be good.

**Comment by takoz53** [comment]
Alright, I'll look into it, although it might take a while.

**Comment by ftk789** [comment]
take ur time, taking longer makes it better
