### ISSUE TITLE
TTS brian support?

### ISSUE THREAD

**Issue by ftk789** [takoz53/TwitchTTS#8]
ik i'm making A LOT of issues, but is there a way to add brian tts instead of microsoft tts?

**Comment by takoz53** [comment]
Yes. You can use any TTS installed on your computer. You just need to type down your TTS name. Or you use GCP voices, which should be instructed in the Readme. Sadly another person had changed the TTS a bit, so some things seem to be missing, but it should be enough!

**Comment by ftk789** [comment]
alright i'll check it, after i fix this issue i have
