### ISSUE TITLE
Pasted the OAuth but when i execute it, it keeps saying OAuth not added 

### ISSUE THREAD

**Issue by ftk789** [takoz53/TwitchTTS#9]
![image](https://user-images.githubusercontent.com/57598907/129485674-cf7c40ce-8fbc-4683-b24d-4e729a3ca292.png)

**Comment by takoz53** [comment]
Right now I am not at home. I'll give it a check when I come back. Your oAuth should be looking something like so: oauth:kdj7Snxla5w...
from the previous oauth:yourauthkey

**Comment by ftk789** [comment]
wonderful, added on discord

**Comment by takoz53** [comment]
User-side issue.
